name: ${pluginName}
main: com.github.maxopoly.KiraBukkitGateway.KiraBukkitGatewayPlugin
author: Maxopoly
version: ${version}
depend: [LuckPerms, CivModCore, NameLayer, CivChat2]
description: ${description}
api-version: ${api_version}
permissions:
    kira.public:
        default: true
    kira.op:
        default: op       
